### ISSUE TITLE
How to use SesSendEmail?

### ISSUE THREAD

**Issue by sinosoidal** [pcolby/aws-sdk-qt#13]
Hi,

I see you have SesClient implemented but how do you use it? How do I send an email?
How do you create a SesSendEmailRequest?

Thx

**Comment by pcolby** [comment]
Hi @sinosoidal, the library is still in early stages of development - it includes much of the basic framework plumbing required for implementing asynchronous AWS clients, including generic classes for managing the building of AWS requests and processing of AWS responses, but none of the individual services classes are implemented / ready yet.  They will be, one day, but will take a long time yet (it's a big job).  Of course, happy for you to help if you can! :)

Cheers.
