### ISSUE TITLE
Qt 5.2 x64 |  error: unused variable ‘d’ [-Werror=unused-variable]

### ISSUE THREAD

**Issue by sarathjeeva** [pcolby/aws-sdk-qt#18]
g++ -c -m64 -pipe -O2 -Wall -W -Werror -D_REENTRANT -fPIC -DQTAWS_LIBRARY -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../../aws-sdk-qt-master/src/AWSMigrationHub -I../../../aws-sdk-qt-master/src -I/usr/include/qt5 -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -Irelease -I. -o release/associatecreatedartifactresponse.o ../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.cpp
In file included from /usr/include/qt5/QtCore/qiodevice.h:45:0,
                 from /usr/include/qt5/QtCore/QIODevice:1,
                 from /usr/include/qt5/QtNetwork/qnetworkreply.h:45,
                 from /usr/include/qt5/QtNetwork/QNetworkReply:1,
                 from ../../../aws-sdk-qt-master/src/core/awsabstractresponse.h:25,
                 from ../../../aws-sdk-qt-master/src/AWSMigrationHub/migrationhubresponse.h:23,
                 from ../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.h:23,
                 from ../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.cpp:20:
../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.cpp: In member function ‘virtual void QtAws::MigrationHub::AssociateCreatedArtifactResponse::parseSuccess(QIODevice&)’:
/usr/include/qt5/QtCore/qglobal.h:936:43: error: unused variable ‘d’ [-Werror=unused-variable]
 #define Q_D(Class) Class##Private * const d = d_func()
                                           ^
../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.cpp:68:5: note: in expansion of macro ‘Q_D’
     Q_D(AssociateCreatedArtifactResponse);
     ^
../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.cpp: At global scope:
../../../aws-sdk-qt-master/src/AWSMigrationHub/associatecreatedartifactresponse.cpp:99:6: error: unused parameter ‘xml’ [-Werror=unused-parameter]
 void AssociateCreatedArtifactResponsePrivate::parseAssociateCreatedArtifactResponse(QXmlStreamReader &xml)
      ^
cc1plus: all warnings being treated as errors
make[3]: *** [release/associatecreatedartifactresponse.o] Error 1
make[3]: Leaving directory `/home/sarathkumar/mqtt/build/src/AWSMigrationHub'
make[2]: *** [release] Error 2
make[2]: Leaving directory `/home/sarathkumar/mqtt/build/src/AWSMigrationHub'
make[1]: *** [sub-AWSMigrationHub-AWSMigrationHub-pro-make_first] Error 2
make[1]: Leaving directory `/home/sarathkumar/mqtt/build/src'
make: *** [sub-src-make_first-ordered] Error 2

**Comment by pcolby** [comment]
Hi @sarathjeeva, there's been ~38 commits pushed to `master` since you created this issue.  I expect the above error has been fixed along the way. Please try bulding with the current (or more recent) head, eg https://github.com/pcolby/aws-sdk-qt/tree/bf4900410639b38f8574cb29b6aa6c293b6ea46a

Thanks :smile:

**Comment by pcolby** [comment]
Assuming this is resolved now.  Feel free to re-open if not. Cheers.

**Comment by sarathjeeva** [comment]
Its solved now. thank you.
