### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by mzanetti** [pcolby/aws-sdk-qt#20]
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeAccountLimitsResponse* QtAws::AutoScaling::AutoScalingClient::describeAccountLimits()’:
../../../src/autoscaling/autoscalingclient.cpp:549:63: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeAccountLimitsResponse *>(send());
                                                               ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeAdjustmentTypesResponse* QtAws::AutoScaling::AutoScalingClient::describeAdjustmentTypes()’:
../../../src/autoscaling/autoscalingclient.cpp:562:65: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeAdjustmentTypesResponse *>(send());
                                                                 ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeAutoScalingNotificationTypesResponse* QtAws::AutoScaling::AutoScalingClient::describeAutoScalingNotificationTypes()’:
../../../src/autoscaling/autoscalingclient.cpp:601:78: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeAutoScalingNotificationTypesResponse *>(send());
                                                                              ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeLifecycleHookTypesResponse* QtAws::AutoScaling::AutoScalingClient::describeLifecycleHookTypes()’:
../../../src/autoscaling/autoscalingclient.cpp:627:68: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeLifecycleHookTypesResponse *>(send());
                                                                    ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeMetricCollectionTypesResponse* QtAws::AutoScaling::AutoScalingClient::describeMetricCollectionTypes()’:
../../../src/autoscaling/autoscalingclient.cpp:689:71: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeMetricCollectionTypesResponse *>(send());
                                                                       ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeScalingProcessTypesResponse* QtAws::AutoScaling::AutoScalingClient::describeScalingProcessTypes()’:
../../../src/autoscaling/autoscalingclient.cpp:741:69: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeScalingProcessTypesResponse *>(send());
                                                                     ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided
../../../src/autoscaling/autoscalingclient.cpp: In member function ‘QtAws::AutoScaling::DescribeTerminationPolicyTypesResponse* QtAws::AutoScaling::AutoScalingClient::describeTerminationPolicyTypes()’:
../../../src/autoscaling/autoscalingclient.cpp:792:72: error: no matching function for call to ‘QtAws::AutoScaling::AutoScalingClient::send()’
     return qobject_cast<DescribeTerminationPolicyTypesResponse *>(send());
                                                                        ^
In file included from ../../../src/autoscaling/autoscalingclient.h:23:0,
                 from ../../../src/autoscaling/autoscalingclient.cpp:20:
../../../src/core/awsabstractclient.h:52:35: note: candidate: virtual QtAws::Core::AwsAbstractResponse* QtAws::Core::AwsAbstractClient::send(const QtAws::Core::AwsAbstractRequest&)
     virtual AwsAbstractResponse * send(const AwsAbstractRequest &request);
                                   ^~~~
../../../src/core/awsabstractclient.h:52:35: note:   candidate expects 1 argument, 0 provided

**Comment by pcolby** [comment]
Thanks @mzanetti, this should be fixed now. Cheers.

**Comment by sergey-sukiyazov** [comment]
Hi!
I have compilation errors also, but in different place (the errors above are fixed for me):
v~~~
g++ -c -pipe -g -Wall -W -Werror -D_REENTRANT -fPIC -DQTAWS_LIBRARY -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../aws-sdk-qt/src/s3 -I. -I../../../aws-sdk-qt/src -I/opt/Qt5/5.11.1/gcc_64/include -I/opt/Qt5/5.11.1/gcc_64/include/QtNetwork -I/opt/Qt5/5.11.1/gcc_64/include/QtCore -Idebug -I/opt/Qt5/5.11.1/gcc_64/mkspecs/linux-g++ -o debug/s3client.o ../../../aws-sdk-qt/src/s3/s3client.cpp
../../../aws-sdk-qt/src/s3/s3client.cpp: In constructor ‘QtAws::S3::S3ClientPrivate::S3ClientPrivate(QtAws::S3::S3Client*)’:
../../../aws-sdk-qt/src/s3/s3client.cpp:1331:21: error: expected type-specifier
     signature = new QtAws::Core::AwsSignatureS3();
                     ^~~~~
Makefile.Debug:26429: recipe for target 'debug/s3client.o' failed
^~~~

I can find only `QtAws::Core::AwsSignatureS2()` and `QtAws::Core::AwsSignatureS4()` in the source codes.

Similar errors were in the different place of code - tere `QtAws::Core::AwsSignatureS2()` was required, but i solved them  and continued build with the patch below (not sure if it's, correct, just replace include files):
v~~~
diff --git a/src/importexport/importexportclient.cpp b/src/importexport/importexportclient.cpp
index 3a731aba3d..c56e5c1bc1 100644
--- a/src/importexport/importexportclient.cpp
+++ b/src/importexport/importexportclient.cpp
@@ -20,7 +20,7 @@
 #include "importexportclient.h"
 #include "importexportclient_p.h"
 
-#include "core/awssignaturev4.h"
+#include "core/awssignaturev2.h"
 #include "canceljobrequest.h"
 #include "canceljobresponse.h"
 #include "createjobrequest.h"
diff --git a/src/simpledb/simpledbclient.cpp b/src/simpledb/simpledbclient.cpp
index 1c335b65bb..a7039c010b 100644
--- a/src/simpledb/simpledbclient.cpp
+++ b/src/simpledb/simpledbclient.cpp
@@ -20,7 +20,7 @@
 #include "simpledbclient.h"
 #include "simpledbclient_p.h"
 
-#include "core/awssignaturev4.h"
+#include "core/awssignaturev2.h"
 #include "batchdeleteattributesrequest.h"
 #include "batchdeleteattributesresponse.h"
 #include "batchputattributesrequest.h"
^~~~

**Comment by pcolby** [comment]
Thanks @sergey-sukiyazov, this is an interesting one... seems the templating engine is messing up for s3 only.  Quite curious... :)  I'll take a look.

**Comment by pcolby** [comment]
Interestingly, this is because Amazon's API description for S3 specifies an invalid signature version `s3` [see here](https://github.com/aws/aws-sdk-cpp/blob/master/code-generation/api-descriptions/s3-2006-03-01.normal.json#L12). Presumably to allow for the fact that some S3 requests are authenticated (using V4 signatures), and some are unauthenticated?

I've checked, and S3 is the only service that does not specify either V2 or V3 as the signature version currently.

```
paul@paul-XPS-13-9343:~/src/aws-sdk-qt/codegen/aws-sdk-cpp/code-generation/api-descriptions$ sed -nre 's/\s*"signatureVersion":\s*//p' *.json | sort | uniq -c
      1 "s3",
      2 "v2",
      7 "v4"
```
I'll add a special case to use V4 signatures for S3 for now, and consider how to support unauthenticated S3 requests later.

**Comment by sergey-sukiyazov** [comment]
Thanks @pcolby :) good job!

how about `importexportclient.cpp` and `simpledbclient.cpp` ? because i have errors there also, but error about the `QtAws::Core::AwsSignatureV2()` not found until i change the include fle names from `awssignaturev4.h` to `awssignaturev2.h` 

see, patch in my comment above

**Comment by pcolby** [comment]
> how about importexportclient.cpp and simpledbclient.cpp

Sorry @sergey-sukiyazov, clearly I didn't read your post all the way through :)
Should be fixed now :)

**Comment by sergey-sukiyazov** [comment]
Thanks @pcolby :) good job! now it's fixed

So, i compiled sources successfully but stuck on compiling tests:
```
 g++ -c -pipe -g -Wall -W -Werror -D_REENTRANT -fPIC -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../aws-sdk-qt/test/cli -I. -I../../../aws-sdk-qt/src -I/opt/Qt5/5.11.1/gcc_64/include -I/opt/Qt5/5.11.1/gcc_64/include/QtNetwork -I/opt/Qt5/5.11.1/gcc_64/include/QtCore -I../../debug/aws-tmp -I/opt/Qt5/5.11.1/gcc_64/mkspecs/linux-g++ -o ../../debug/aws-tmp/cli.o ../../../aws-sdk-qt/test/cli/cli.cpp
../../../aws-sdk-qt/test/cli/cli.cpp:23:10: fatal error: sqs/sqscreatequeueresponse.h: Нет такого файла или каталога
 #include <sqs/sqscreatequeueresponse.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile.Debug:392: recipe for target '../../debug/aws-tmp/cli.o' failed
make[3]: *** [../../debug/aws-tmp/cli.o] Error 1
make[3]: выход из каталога «/mnt/disk-3/sergey/Work/Sources.1/aws-sdk-qt-build/test/cli»
```
it seems that required headers is in the `sqs-old/` subderictory. Can you check this also? Thanks.

NOTE:
i also added `"QMAKE_CXXFLAGS+=-Wno-comment"`, becouse couple of subdirectories failed on `/*` text in samples pathes inside the C-style comments, it's under Ubuntu 18.04 LTS and gcc 7.3.0
```
$ g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
maybe this info will be helpful for You.

**Comment by pcolby** [comment]
This is really old, and the project has since moved from `qmake` to `cmake`, so I'll close this now.  Feel free to re-open, or create a new issue if you're still having build issues. Cheers.
